# Generated by Django 5.1.6 on 2025-02-19 07:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=150)),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('package_inclusion', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), size=None)),
            ],
        ),
    ]
