# Generated by Django 5.1.6 on 2025-03-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_awards_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='Untitled Project', max_length=150),
        ),
    ]
