# Generated by Django 5.1.6 on 2025-02-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_rename_packages_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
