# Generated by Django 5.1.6 on 2025-03-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_project_description_project_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=150),
        ),
    ]
