# Generated by Django 5.1.6 on 2025-03-30 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_awards_description_alter_project_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='alt',
        ),
    ]
