# Generated by Django 5.1.6 on 2025-02-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('custom', 'Custom')], default='fixed', max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
