# Generated by Django 5.1.6 on 2025-02-27 07:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0010_package_package_type_alter_package_package_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_inclusion',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), null=True, size=None),
        ),
    ]
