# Generated by Django 5.1.6 on 2025-03-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0011_alter_package_package_inclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_downpayment',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=8),
            preserve_default=False,
        ),
    ]
