# Generated by Django 5.1.6 on 2025-03-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0012_package_package_downpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('custom', 'Custom')], default='Fixed', max_length=10),
        ),
    ]
