# Generated by Django 5.1.6 on 2025-03-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0013_alter_package_package_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=150)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
