# Generated by Django 5.1.6 on 2025-03-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0014_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='package_downpayment',
        ),
        migrations.RemoveField(
            model_name='package',
            name='package_inclusion',
        ),
        migrations.AddField(
            model_name='package',
            name='services',
            field=models.ManyToManyField(blank=True, to='organizer.services'),
        ),
    ]
