# Generated by Django 5.1.6 on 2025-03-07 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0015_remove_package_package_downpayment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='package_price',
        ),
    ]
