# Generated by Django 5.1.6 on 2025-03-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0016_remove_package_package_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
