# Generated by Django 5.1.6 on 2025-02-27 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0010_package_package_type_alter_package_package_name'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_user_email', to=settings.AUTH_USER_MODEL)),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_user_fullname', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.package')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
