# Generated by Django 5.1.6 on 2025-02-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_booking_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
