# Generated by Django 5.1.6 on 2025-04-20 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_activitylogs'),
        ('user', '0003_alter_userprofile_profile_img_bookedservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedservice',
            name='service_name',
        ),
        migrations.AddField(
            model_name='bookedservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.services'),
        ),
    ]
