# Generated by Django 5.1.6 on 2025-02-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
