# Generated by Django 5.1.6 on 2025-04-20 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_activitylogs'),
        ('user', '0004_remove_bookedservice_service_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.services'),
        ),
    ]
