# Generated by Django 5.1.6 on 2025-02-27 11:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizer', '0011_alter_package_package_inclusion'),
        ('user', '0005_delete_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, max_length=6, null=True, unique=True)),
                ('wedding_date', models.DateField()),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_20_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('receipt_img', models.ImageField(upload_to='')),
                ('is_paid', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
