# Generated by Django 5.1.6 on 2025-04-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_bookedservice_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedservice',
            name='service',
        ),
        migrations.AddField(
            model_name='bookedservice',
            name='service_name',
            field=models.CharField(default='default service', max_length=150),
            preserve_default=False,
        ),
    ]
