# Generated by Django 5.1.6 on 2025-02-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='receipt_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
