# Generated by Django 5.1.6 on 2025-02-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_booking_receipt_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='receipt_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
