# Generated by Django 5.1.6 on 2025-02-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_booking_receipt_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_paid',
            new_name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='price_20_percent',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='receipt_img',
        ),
    ]
