# Generated by Django 5.1.6 on 2025-02-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_is_paid_booking_is_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(editable=False, max_length=100, null=True, unique=True),
        ),
    ]
