# Generated by Django 5.1.6 on 2025-03-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amout_paid',
            new_name='amount_paid',
        ),
    ]
