# Generated by Django 5.1.6 on 2025-03-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_amout_paid_payment_amount_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='transcation_id',
            new_name='transaction_id',
        ),
    ]
