# Generated by Django 5.1.6 on 2025-03-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_transcation_id_payment_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='total_price',
            new_name='package_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('successful', 'Successful')], max_length=50),
        ),
    ]
