# Generated by Django 5.1.6 on 2025-03-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_total_price_booking_package_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(),
        ),
    ]
