# Generated by Django 5.1.6 on 2025-03-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
    ]
