# Generated by Django 5.1.6 on 2025-03-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0015_remove_package_package_downpayment_and_more'),
        ('user', '0018_booking_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_services',
            field=models.ManyToManyField(blank=True, to='organizer.services'),
        ),
    ]
