# Generated by Django 5.1.6 on 2025-03-13 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
    ]
